portfolio_analysis:
  description: >
    Analyze wallet {wallet_address} across {networks} networks. Use PortfolioTool for holdings, 
    TokenPriceTool for prices, SearchTool for market context. Calculate allocations by asset class 
    (L1, DeFi, stablecoins), risk metrics (HHI, volatility), performance (7d/30d/90d returns vs ETH/BTC), 
    and identify anomalies (>15% positions, unusual protocols).
  expected_output: >
    # Portfolio Analysis: {wallet_address}
    ## 1. Summary: Total value, 30d change, key risks, top findings
    ## 2. Composition: Asset allocation %, network distribution, top 10 holdings
    ## 3. Risk: Concentration (HHI), volatility, correlation matrix, smart contract risk
    ## 4. Performance: Returns vs benchmarks, alpha contributors, Sharpe ratio
    ## 5. Optimization: Diversification, risk mitigation, yield optimization, rebalancing
  agent: portfolio_intelligence_analyst

transaction_carbon_analysis:
  description: >
    Analyze transaction patterns and carbon footprint for {wallet_address} across {networks}. 
    Use MoralisTransactionTool for transaction data, CarbonFootprintTool for emissions. 
    Calculate total gas usage, CO2 emissions by network, transaction patterns (frequency, types, timing), 
    and provide reduction strategies (L2 migration, batching, protocol switching).
  expected_output: >
    # Transaction & Carbon Analysis: {wallet_address}
    ## 1. Summary: Transaction count, networks used, total gas, timeframe
    ## 2. Carbon Footprint: Total CO2/energy, emissions by network, impact rating
    ## 3. Patterns: Frequency, peak times, transaction types, gas strategy
    ## 4. Context: Trees to offset, car miles equivalent, vs average user
    ## 5. Optimization: L2 migration, batching, protocol switching (High/Medium/Low priority)
    ## 6. Actions: Immediate (7 days), short-term (1-3 months), long-term plan
    ## 7. Projections: Annual emissions, potential reduction, cost-benefit
    ## 8. Monitoring: KPIs, tracking frequency, benchmarks
  agent: transaction_carbon_analyst

comprehensive_intelligence_report:
  description: >
    Synthesize portfolio and transaction analyses into strategic intelligence. Map connections 
    between holdings and behaviors, categorize strategy (DeFi farmer, holder, etc.), benchmark 
    performance vs peers, aggregate risk factors, identify relationship patterns, and create 
    prioritized action plan with monitoring framework.
  expected_output: >
    # Comprehensive Intelligence Report: {wallet_address}
    ## 1. Executive: Strategy classification, performance snapshot, risk/opportunity matrix, key insights
    ## 2. Performance: Consolidated metrics, peer comparison, alpha/beta attribution, projections
    ## 3. Behavioral: Decision patterns, risk tolerance, timing effectiveness, environmental consciousness
    ## 4. Relationships: Ecosystem positioning, counterparties, capital flows, influence assessment
    ## 5. Risk: Comprehensive dashboard, systemic vulnerabilities, concentration, security, regulatory
    ## 6. Environmental: Carbon summary, network efficiency, sustainability score, reduction opportunities
    ## 7. Action Plan: Prioritized opportunities, quick wins, strategic initiatives, carbon roadmap
    ## 8. Value: Optimization potential, risk-adjusted returns, carbon neutrality pathway, sustainability
  agent: strategic_intelligence_synthesizer